PUT http://localhost:3000/api/arduino-configurations
Content-Type: application/json

{
  "uuid": "0fce3005-0189-46f5-b522-02c28f5d2a8c",
  "name": "Arduino UNO Test",
  "serialport": "COM4",
  "pinouts": [
    {
      "type": "SCHEDULE",
      "sensors": [],
      "valves": [
        11
      ]
    }
  ]
}
